# **Tugas 1 - Dissimilarity**

In [ ]:
#awal mengimpor library pandas, lalu menampilkan data yang sudah di upload di google drive
import pandas as pd 
data = pd.read_csv('/content/drive/MyDrive/Classroom/Data Meaning/tugas/tugas 1/archive (2).zip')
data.head(5)

,Title,Book_category,Star_rating,Price,Stock,Quantity
0,A Light in the Attic,Poetry,Three,51.77,In stock,22
1,Tipping the Velvet,Historical Fiction,One,53.74,In stock,20
2,Soumission,Fiction,One,50.10,In stock,20
3,Sharp Objects,Mystery,Four,47.82,In stock,20
4,Sapiens: A Brief History of Humankind,History,Five,54.23,In stock,20

In [ ]:
#mengecek tipe data yang ada di data 
data.dtypes

Title             object
Book_category     object
Star_rating       object
Price            float64
Stock             object
Quantity           int64
dtype: object